# Generated by Django 4.2.6 on 2023-12-05 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='glicose',
            name='user',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='user',
        ),
        migrations.RemoveField(
            model_name='medicamento',
            name='user',
        ),
        migrations.DeleteModel(
            name='AtividadeFisica',
        ),
        migrations.DeleteModel(
            name='Glicose',
        ),
        migrations.DeleteModel(
            name='Meal',
        ),
        migrations.DeleteModel(
            name='Medicamento',
        ),
    ]
