# Generated by Django 4.2.6 on 2023-12-05 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_glicose_user_remove_meal_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campeonato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
                ('ano', models.IntegerField()),
                ('serie', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='estadio',
            name='id_estadio',
        ),
        migrations.RemoveField(
            model_name='tecnico',
            name='id_tecnico',
        ),
        migrations.AddField(
            model_name='equipe',
            name='estadio',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='tasks.estadio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipe',
            name='tecnico',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='tasks.tecnico'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estadio',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tecnico',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='equipe',
            name='cidade',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='estado',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='nome',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='sigla',
            field=models.CharField(max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='estadio',
            name='pais',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
                ('placar_casa', models.IntegerField(default=0)),
                ('placar_visitante', models.IntegerField(default=0)),
                ('arbitro', models.IntegerField()),
                ('qtd_publico', models.IntegerField(default=0)),
                ('status_fk', models.IntegerField()),
                ('rodada', models.IntegerField()),
                ('turno', models.IntegerField()),
                ('campeonato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.campeonato')),
                ('equipe_casa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas_casa', to='tasks.equipe')),
                ('equipe_visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas_visitante', to='tasks.equipe')),
                ('id_estadio_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.estadio')),
            ],
        ),
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
                ('num_camisa', models.IntegerField()),
                ('idade', models.IntegerField(default=0)),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.equipe')),
            ],
        ),
        migrations.CreateModel(
            name='Escalacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titular', models.IntegerField()),
                ('jogador_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.jogador')),
                ('partida_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.partida')),
            ],
        ),
        migrations.CreateModel(
            name='Desempenho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gols', models.IntegerField(default=0)),
                ('cartao_amarelo', models.IntegerField(default=0)),
                ('cartao_vermelho', models.IntegerField(default=0)),
                ('id_jogador_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.jogador')),
                ('id_partida_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.partida')),
            ],
        ),
    ]
