# Generated by Django 4.2.6 on 2023-12-06 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_campeonato_serie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='desempenho',
            old_name='id_jogador_fk',
            new_name='jogador_id',
        ),
        migrations.RenameField(
            model_name='desempenho',
            old_name='id_partida_fk',
            new_name='partida_id',
        ),
        migrations.RenameField(
            model_name='escalacao',
            old_name='jogador_fk',
            new_name='jogador_id',
        ),
        migrations.RenameField(
            model_name='escalacao',
            old_name='partida_fk',
            new_name='partida_id',
        ),
        migrations.RenameField(
            model_name='partida',
            old_name='equipe_casa',
            new_name='equipe_casa_id',
        ),
        migrations.RenameField(
            model_name='partida',
            old_name='equipe_visitante',
            new_name='equipe_visitante_id',
        ),
        migrations.RenameField(
            model_name='partida',
            old_name='id_estadio_fk',
            new_name='estadio_id',
        ),
        migrations.RenameField(
            model_name='partida',
            old_name='status_fk',
            new_name='status',
        ),
        migrations.AddField(
            model_name='desempenho',
            name='chutes_a_gol',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='desempenho',
            name='defesas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='desempenho',
            name='faltas_cometidas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='desempenho',
            name='faltas_recebidas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jogador',
            name='posicao',
            field=models.CharField(choices=[('CA', 'Centroavante'), ('MA', 'Meia Atacante'), ('AD', 'Avançado Direito'), ('MC', 'Meio de Campo Central'), ('ME', 'Meia Esquerda'), ('LE', 'Lateral Esquerdo'), ('ZC', 'Zagueiro Central'), ('LD', 'Lateral Direito'), ('GL', 'Goleiro'), ('VO', 'Volante'), ('AE', 'Avançado Esquerdo')], default='Desconhecido', max_length=2),
        ),
        migrations.AddField(
            model_name='jogador',
            name='posicao_selecionada',
            field=models.CharField(blank=True, choices=[('CA', 'Centroavante'), ('MA', 'Meia Atacante'), ('AD', 'Avançado Direito'), ('MC', 'Meio de Campo Central'), ('ME', 'Meia Esquerda'), ('LE', 'Lateral Esquerdo'), ('ZC', 'Zagueiro Central'), ('LD', 'Lateral Direito'), ('GL', 'Goleiro'), ('VO', 'Volante'), ('AE', 'Avançado Esquerdo')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='desempenho',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='escalacao',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='escalacao',
            name='titular',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Substituicao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('min_partida', models.IntegerField()),
                ('entrando_jogador_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substituicoes_entrando', to='tasks.jogador')),
                ('partida_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.partida')),
                ('saindo_jogador_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substituicoes_saindo', to='tasks.jogador')),
            ],
        ),
    ]
