# Generated by Django 4.2.6 on 2023-12-07 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_rename_id_jogador_fk_desempenho_jogador_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jogador',
            name='posicao',
        ),
    ]
